### ISSUE TITLE
button grayed out

### ISSUE THREAD

**Issue by marianocatalano** [sql-bi/AnalyzeInExcel#5]
Hi Marco, great idea, I am used to to this same technique but manually, finding out the SSAS Tabular port.
The button is grayed out.
I installed using the MSI you posted in the previous issue.
Mariano

**Comment by marcosqlbi** [comment]
Go to Preview features in Power BI, check "Store datasets using enhanced metadata format", and restart Power BI, that must fix the problem, showing external tools enabled.
Let me know if this fixes the problem.

**Comment by marianocatalano** [comment]
Hi Marco, I applied the changes you mentioned and it is working now.
When Power BI Desktop is closed, and then opened again, the SSAS Tabular port will change. To refresh the objects created in a previous session, is changing the port in the connection properties the best approach to reconnect ?

**Comment by marcosqlbi** [comment]
Currently yes - in future versions of Analyze in Excel we should implement techniques to refresh the connection automatically.
