### ISSUE TITLE
Cannot add any field to Values area of pivot table

### ISSUE THREAD

**Issue by mau-lopez** [sql-bi/AnalyzeInExcel#6]
I have not been able to add any numerical field to the Values area of the newly created pivot table. I've checked that in Power BI the field is a formatted

Windows 10 Pro x64 Build 19041.450, Excel Pro Plus 2019 x64  Build 13127.20208, Power BI Desktop x64 July 2020 Ver 2.83.5894.961, x64_15.0.2000.475_SQL_AS_OLEDB

<img width="1198" alt="Annotation 2020-08-19 204348" src="https://user-images.githubusercontent.com/44591974/90707997-62c37000-e25e-11ea-9e74-70f71c653371.png">
 as a decimal number.

**Comment by marcosqlbi** [comment]
This is an expected behavior: when you use Excel, you can only include explicit measures. Excel cannot add to a PivotTable numeric fields as implicit measures like Power BI does. This is the same behavior you have by using Analyze In Excel with a dataset published on powerbi.com.

**Comment by mau-lopez** [comment]
Thanks a lot for the clarification Mr Russo. Regards
